name: MineBuilder
main: de.minebuilder.MineBuilder
version: 0.1
api-version: 1.15
softdepend: [WorldGuard]
commands:
  mbToggleExp:
    description: Enables / Disables the Exp drops.
    usage: /<command> [true,false]
    permission-message: You don't have <permissions>
  mbAddBreak:
    description: use /mbgetid and then this to add a block which drops exp on break.
    usage: /<command> <minEXP> <maxEXP> <count>
    permission-message: You don't have <permissions>
  mbAddPlace:
    description: use /mbgetid and then this to add a block which drops exp on place.
    usage: /<command> <minEXP> <maxEXP> <count>
    permission-message: You don't have <permissions>
  mbAddKill:
    description: use /mbgetid and then this to set the exp a Mob drops exp on kill.
    usage: /<command> <minEXP> <maxEXP> <count>
    permission-message: You don't have <permissions>
  mbGetId:
    description: Click on something and get the name + ID
    usage: /<command>
    permission-message: You don't have <permissions>
  mbLoadCfg:
    description: reloads the config
    usage: /<command>
    permission-message: You don't have <permissions>