name: MineBuilder
main: de.minebuilder.MineBuilder
version: 0.1
commands:
  mbToggleExp:
    description: Enables / Disables the Exp drops.
    usage: /<command> [true,false]
    permission-message: You don't have <permissions>
  mbAdd:
    description: Click on something and add it to the specified config. EventIDs  0 - break block  1 - place block
    usage: /<command> <eventID zurzeit nur 0> <BlockName> <BlockID> <minEXP> <maxEXP> <count>
    permission-message: You don't have <permissions>
  mbGetId:
      description: Click on something and get the name + ID
      usage: /<command>
      permission-message: You don't have <permissions>